### ISSUE TITLE
error installing the package

### ISSUE THREAD

**Issue by LiNk-NY** [RiboRings/iSEEtree#38]
Hi Giulio, @RiboRings 

I am getting this error when trying to install `iSEEtree` from source 

```r
Error in rematchDefinition(definition, fdef, mnames, fnames, signature) : 
  methods can add arguments to the generic '.multiSelectionResponsive' only if '...' is an argument to the generic
Error: unable to load R code in package 'iSEEtree'
Execution halted
```

`Version: 1.1.0`

https://bioconductor.org/checkResults/devel/bioc-LATEST/iSEEtree/nebbiolo1-install.html

-Marcel

**Comment by RiboRings** [comment]
Hi Marcel!

Thank you for reporting the problem.

The error is caused by a renamed argument of the `.multiSelectionResponsive` method inherited from iSEE. The related commit is https://github.com/iSEE/iSEE/commit/3adb21cfcefd1c99128d00fc1c744191231926ca.

After merging https://github.com/microbiome/iSEEtree/pull/39, the bug should get fixed.

Best,
Giulio

**Comment by RiboRings** [comment]
Feel free to reopen this issue if bug persists.
